### ISSUE TITLE
runAsUser 后不能在 HOME 目录下创建文件

### ISSUE THREAD

**Issue by zh794390558** [uniatlas/atlasctl#26]
`pip install XXX --user `  提示无权限创建目录。

**Comment by zh794390558** [comment]
#https://github.com/coreos/tectonic-installer/issues/959
#https://github.com/coreos/tectonic-installer/pull/962

**Comment by zh794390558** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  labels: 
    k8s-app: etcd-operator
  name: etcd-operator
  namespace: kube-system
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        k8s-app: etcd-operator
    spec: 
      containers: 
        - env: 
            - name: MY_POD_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
            - name: HOME
              value: /tmp
          image: ${etcd_operator_image}
          name: etcd-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```
